// Generated by CoffeeScript 1.10.0
(function() {
  switch (table) {
    case "tabSistematici":
      draw_journal_diagram();
      break;
    default:
      d3.select('#visualization').remove();
  }

}).call(this);
