// Generated by CoffeeScript 1.10.0
(function() {
  var container, enter_examples, examples;

  d3.select('#central_section_title').text("Some examples of resources classified as " + (data[0].uri.split('/').slice(-2)[0]) + ":");

  container = d3.select('#examples');

  examples = container.selectAll('.example').data(data.sort(function(a, b) {
    a = a.uri.split('/');
    b = b.uri.split('/');
    return d3.ascending(parseInt(a[a.length - 1]), parseInt(b[b.length - 1]));
  }));

  enter_examples = examples.enter().append('div').attr({
    "class": 'example'
  });

  enter_examples.append('div').attr({
    "class": 'title'
  }).html(function(d) {
    return d.label;
  });

  enter_examples.append('div').attr({
    "class": 'uri'
  }).append('a').attr({
    href: function(d) {
      return d.uri;
    }
  }).text(function(d) {
    return d.uri;
  });

}).call(this);
