// Generated by CoffeeScript 1.10.0
(function() {
  var classes, container, enter_classes;

  container = d3.select('#classes');

  classes = container.selectAll('.class').data(data);

  enter_classes = classes.enter().append('a').attr({
    href: function(d) {
      return home_url + "directory/" + d.table;
    }
  }).append('div').attr({
    "class": 'class'
  });

  enter_classes.append('div').attr({
    "class": 'title'
  }).text(function(d) {
    return d["class"];
  });

  enter_classes.append('div').attr({
    "class": 'description'
  }).text(function(d) {
    return d.desc;
  });

}).call(this);
