// Generated by CoffeeScript 1.10.0
(function() {
  var bar_height, class_height, classes_amounts, left_padding, svg;

  left_padding = 40;

  class_height = 60;

  bar_height = 5;

  classes_amounts = {};

  svg = d3.select('svg').attr({
    height: data.length * class_height
  }).append('g').attr({
    transform: "translate(0, 20)"
  });

  d3.json(home_url + "snorql/classes.json", function(classes_data) {
    var bar_width, c, classes, enter_classes, i, key, ref;
    ref = classes_data.results.bindings;
    for (i in ref) {
      c = ref[i];
      key = c.c.value.split('/').slice(-1)[0].replace('#', '');
      if (key === 'Person' || key === 'Organization') {
        key = 'Agent';
      } else if (key === 'Location') {
        key = 'Country';
      }
      classes_amounts[key] = parseInt(c.cont.value);
    }
    bar_width = d3.scale.pow().exponent(0.3).range([0, d3.select('#central_section').node().getBoundingClientRect().width / 2]).domain([
      0, d3.max(classes_data.results.bindings, function(d) {
        return parseInt(d.cont.value);
      })
    ]);
    classes = svg.selectAll('.class').data(data);
    enter_classes = classes.enter().append('g').attr({
      "class": 'class'
    });
    classes.append('text').attr({
      "class": 'title',
      x: left_padding,
      y: function(d, i) {
        return i * class_height;
      }
    }).html(function(d) {
      return "<a xlink:href='" + home_url + "directory/" + d.table + "'>" + d["class"] + "</a>:";
    });
    classes.append('text').attr({
      "class": 'description',
      x: function(d) {
        return left_padding + 5 + d3.select(this.parentNode).select('.title').node().getBoundingClientRect().width;
      },
      y: function(d, i) {
        return i * class_height;
      }
    }).text(function(d) {
      return d.desc;
    });
    classes.append('rect').attr({
      "class": 'bar',
      x: left_padding,
      y: function(d, i) {
        return i * class_height + 10;
      },
      width: function(d) {
        return bar_width(classes_amounts[d["class"].replace(/ /g, '')]);
      },
      height: bar_height
    });
    return classes.append('text').attr({
      "class": 'bar_amount',
      x: function(d) {
        return left_padding;
      },
      y: function(d, i) {
        return i * class_height + 27;
      }
    }).text(function(d) {
      return classes_amounts[d["class"].replace(/ /g, '')] + " instances";
    });
  });


  /*container = d3.select '#classes'
  
  classes = container.selectAll '.class'
    .data data
  
  enter_classes = classes.enter()
      .append 'a'
        .attr
          href: (d) -> "#{home_url}directory/#{d.table}"
        .append 'div'
          .attr
            class: 'class'
  
  enter_classes.append 'div'
    .attr
      class: 'title'
    .text (d) -> d.class
  
  enter_classes.append 'div'
    .attr
      class: 'description'
    .text (d) -> d.desc
   */

}).call(this);
