// Generated by CoffeeScript 1.10.0
(function() {
  var bar_height, class_height, classes_amounts, left_padding, svg;

  left_padding = 150;

  class_height = 30;

  bar_height = 15;

  classes_amounts = {};

  svg = d3.select('svg').attr({
    height: data.length * class_height
  }).append('g').attr({
    transform: "translate(0, 20)"
  });

  d3.json(home_url + "snorql/classes.json", function(classes_data) {
    var c, classes, i, key, ref, x, y;
    ref = classes_data.results.bindings;
    for (i in ref) {
      c = ref[i];
      key = c.c.value.split('/').slice(-1)[0].replace('#', '');
      if (key === 'Person' || key === 'Organization') {
        key = 'Agent';
      } else if (key === 'Location') {
        key = 'Country';
      }
      classes_amounts[key] = parseInt(c.cont.value);
    }
    x = d3.scale.pow().exponent(0.3).range([0, d3.select('#central_section').node().getBoundingClientRect().width / 2]).domain([
      0, d3.max(classes_data.results.bindings, function(d) {
        return parseInt(d.cont.value);
      })
    ]);
    y = d3.scale.ordinal().rangeRoundBands([0, 300], .5).domain(data.map(function(d, i) {
      return i;
    }));

    /* Classes
     */
    classes = svg.selectAll('.class').data(data);
    classes.enter().append('g').attr({
      "class": 'class'
    });
    classes.append('rect').attr({
      "class": 'bar',
      x: left_padding,
      y: function(d, i) {
        return y(i);
      },
      width: function(d) {
        return x(classes_amounts[d["class"].replace(/ /g, '')]);
      },
      height: bar_height
    });
    classes.append('text').attr({
      'text-anchor': 'end',
      x: left_padding - 10,
      y: function(d, i) {
        return y(i) + bar_height / 1.4;
      }
    }).html(function(d) {
      return "<a class='title' xlink:href='" + home_url + "directory/" + d.table + "'>" + d["class"] + "</a>";
    }).append('title').text(function(d) {
      return "" + d.desc;
    });
    return classes.append('text').attr({
      "class": 'bar_amount',
      x: function(d) {
        return left_padding + x(classes_amounts[d["class"].replace(/ /g, '')]) + 5;
      },
      y: function(d, i) {
        return y(i) + bar_height / 1.4;
      }
    }).text(function(d) {
      return classes_amounts[d["class"].replace(/ /g, '')];
    }).append('title').text(function(d) {
      return classes_amounts[d["class"].replace(/ /g, '')] + " instances of type " + d["class"];
    });
  });

}).call(this);
